name: WASM Build + Deploy

on: [push]

jobs:
  build:
    name: "ğŸ—ï¸ Build WASM"
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v2.3.1
        with:
          submodules: recursive

      - name: ğŸ“¦ Install dependencies
        run: |
          sudo apt-get install -y cmake build-essential

      - name: ğŸ”§ Produce WASM build
        run: |
          bash QMC2-wasm/build-wasm

      - name: ğŸ”§ Produce QMC2-Crypto docs
        run: |
          PUBLIC_DIR="$PWD/public/"
          cd QMC2-wasm/npm
          npm ci
          npm run build:doc
          cp -R docs "$PUBLIC_DIR"
      - name: ğŸš Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: public
          retention-days: 3

  deploy:
    name: "âœˆï¸ Deploy QMC2-WASM..."
    needs: build
    runs-on: ubuntu-22.04

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    steps:
      - name: ğŸš€ Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
