name: WASM Build + Deploy

on: [push]

jobs:
  QMC2-WASM:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v2.3.1
        with:
          submodules: recursive

      - name: ğŸ“¦ Install dependencies
        run: |
          sudo apt-get install -y cmake build-essential

      - name: ğŸ”§ Produce WASM build
        run: |
          bash QMC2-wasm/build-wasm

      - name: ğŸ”§ Produce QMC2-Crypto docs
        run: |
          PUBLIC_DIR="$PWD/public/"
          cd QMC2-wasm/npm
          npm ci
          npm run build:doc
          cp -R docs "$PUBLIC_DIR"

      - name: ğŸš€ Deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: public
